name: Smoke Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"


jobs:
  test:
    name: Smoke Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '1.8'
      - name: Build with Maven
        run: mvn clean test -Dcucumber.options="--tag @smokeTest"
      - uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber.json"
      - name: Deploy report to Github page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish dir: ./public